from langchain_mistralai import ChatMistralAI
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
import os

# Load environment variables (.env)
# Make sure LANGCHAIN_API_KEY and LANGCHAIN_TRACING_V2=true
# are present in your .env file so LangSmith can record traces.
load_dotenv()

# All traces generated from this application
# will be stored under this project in LangSmith.
os.environ['LANGCHAIN_PROJECT'] = 'Sequential LLM App'


# ------------------------- Prompt 1 -------------------------
# This prompt creates a detailed report on the given topic.
# In LangSmith, this appears as one node (Prompt Template)
# inside the execution trace.
prompt1 = PromptTemplate(
    template='Generate a detailed report on {topic}',
    input_variables=['topic']
)


# ------------------------- Prompt 2 -------------------------
# This prompt summarizes the report generated by Prompt 1.
# LangSmith will display this as another prompt node
# connected after the first LLM execution.
prompt2 = PromptTemplate(
    template='Generate a 5 pointer summary from the following text \n {text}',
    input_variables=['text']
)


# ------------------------- Model 1 -------------------------
# First LLM used to generate the detailed report.
# LangSmith records:
# - Model name
# - Input prompt
# - Output response
# - Token usage
# - Latency
model1 = ChatMistralAI(
    model="mistral-small-2506",
    temperature=0.7
)


# ------------------------- Model 2 -------------------------
# Second LLM summarizes the report.
# LangSmith records this as another LLM run.
model2 = ChatMistralAI(
    model="mistral-medium-3.5",
    temperature=0.5
)


# Converts the AIMessage returned by the LLM
# into a plain Python string.
# LangSmith also shows parser execution as a separate run.
parser = StrOutputParser()


# ------------------------- Sequential Chain -------------------------
# Flow:
# Prompt1
#      ↓
# Model1
#      ↓
# Parser
#      ↓
# Prompt2
#      ↓
# Model2
#      ↓
# Parser
#
# LangSmith visualizes this entire pipeline as a parent run
# with each component appearing as child runs.
chain = prompt1 | model1 | parser | prompt2 | model2 | parser


# ------------------------- LangSmith Configuration -------------------------
# This configuration is attached to the trace.
config = {

    # Custom name shown for this execution in LangSmith.
    # Makes it easy to identify this particular run.
    'run_name': 'Sequential Chain',

    # Tags help filter and organize traces.
    # Example:
    # Clicking "llm app" in LangSmith shows all runs
    # containing this tag.
    'tags': [
        'llm app',
        'report generation',
        'summarization'
    ],

    # Metadata stores custom information.
    # This is extremely useful for comparing experiments.
    # It does NOT affect model output.
    'metadata': {
        'model1': 'mistral-small-2506',
        'model1_temp': 0.7,
        'model2': 'mistral-medium-3.5',
        'model2_temp': 0.5,
        'parser': 'StrOutputParser'
    }
}


# ------------------------- Execute Chain -------------------------
# invoke() starts the entire pipeline.
#
# LangSmith records:
# - Input ("Unemployment in India")
# - Every intermediate step
# - Prompt templates
# - LLM calls
# - Parsed outputs
# - Final output
# - Token usage
# - Cost (if available)
# - Latency
# - Metadata
# - Tags
# - Run hierarchy
result = chain.invoke(
    {'topic': 'Unemployment in India'},
    config=config
)

# Final summarized output
print(result)