# pip install -U langchain langchain-mistralai langchain-community faiss-cpu pypdf python-dotenv langsmith

import os
from dotenv import load_dotenv

# --------------------------------------------------------------------
# traceable is a LangSmith decorator.
#
# It creates a CUSTOM TRACE (span/run) for any Python function.
# Normally LangSmith automatically traces only LangChain components
# like LLMs, prompts, retrievers, chains, parsers, etc.
#
# Functions such as:
#   - loading PDFs
#   - splitting documents
#   - creating vector databases
#
# are normal Python functions and are NOT automatically visible in
# LangSmith.
#
# Decorating them with @traceable makes them appear as separate runs
# inside the LangSmith execution graph.
# --------------------------------------------------------------------
from langsmith import traceable

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_mistralai import MistralAIEmbeddings, ChatMistralAI
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import (
    RunnableParallel,
    RunnablePassthrough,
    RunnableLambda
)
from langchain_core.output_parsers import StrOutputParser


# --------------------------------------------------------------------
# Load environment variables.
#
# Your .env should contain:
#
# LANGCHAIN_API_KEY=xxxxxxxx
# LANGCHAIN_TRACING_V2=true
# MISTRAL_API_KEY=xxxxxxxx
#
# LANGCHAIN_TRACING_V2 enables automatic tracing.
# LANGCHAIN_API_KEY authenticates with LangSmith.
# --------------------------------------------------------------------
load_dotenv()


# --------------------------------------------------------------------
# Every trace generated by this application will be grouped under
# the "RAG Chatbot" project inside LangSmith.
#
# This helps organize multiple applications and experiments.
# --------------------------------------------------------------------
os.environ["LANGCHAIN_PROJECT"] = "RAG Chatbot"

PDF_PATH = "islr.pdf"



# ====================================================================
#                  CUSTOM TRACED SETUP FUNCTIONS
# ====================================================================

# --------------------------------------------------------------------
# load_pdf()
#
# Normally this function would execute silently.
#
# Since it is decorated with @traceable, LangSmith creates a child run
# named "load_pdf".
#
# In LangSmith you can inspect:
#
# • Function input
# • Function output
# • Execution time
# • Parent-child relationship
#
# This greatly improves observability.
# --------------------------------------------------------------------
@traceable(name="load_pdf" , tags=["pdf" , "loader"] , metadata={"loader" : "PyPDFLoader"})
def load_pdf(path: str):

    loader = PyPDFLoader(path)

    # Converts every PDF page into a LangChain Document.
    docs = loader.load()

    return docs



# --------------------------------------------------------------------
# split_documents()
#
# Another normal Python function.
#
# LangSmith would NOT show this step unless we decorate it.
#
# With @traceable we can see:
#
# • Number of chunks produced
# • Function latency
# • Function inputs
# • Function outputs
#
# Extremely useful for debugging poor retrieval.
# --------------------------------------------------------------------
@traceable(name="split_documents")
def split_documents(
    docs,
    chunk_size=1000,
    chunk_overlap=150,
):

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap
    )

    splits = splitter.split_documents(docs)

    return splits



# --------------------------------------------------------------------
# build_vectorstore()
#
# Creates embeddings and stores them inside FAISS.
#
# Since this function is traced,
# LangSmith displays it as a separate setup step.
#
# Inside this traced run, LangSmith also automatically traces:
#
# • Embedding model calls
# • Embedding latency
# • Token usage (if available)
#
# making debugging much easier.
# --------------------------------------------------------------------
@traceable(name="build_vectorstore" , tags=["embeddings" , "vectorstore"] , metadata={"embedding model" : "mistral-embed"})
def build_vectorstore(splits):

    emb = MistralAIEmbeddings(
        model="mistral-embed"
    )

    # Every chunk is converted into embeddings
    # and stored in the FAISS vector database.
    vs = FAISS.from_documents(splits, emb)

    return vs



# --------------------------------------------------------------------
# setup_pipeline()
#
# This acts as a PARENT traced function.
#
# Instead of seeing three unrelated functions,
# LangSmith groups:
#
# setup_pipeline
#      │
#      ├── load_pdf
#      ├── split_documents
#      └── build_vectorstore
#
# making the execution graph cleaner.
# --------------------------------------------------------------------
@traceable(name="setup_pipeline")
def setup_pipeline(pdf_path: str):

    docs = load_pdf(pdf_path)

    splits = split_documents(docs)

    vectorstore = build_vectorstore(splits)

    return vectorstore



# ====================================================================
#                         LLM
# ====================================================================

# Mistral model used for answer generation.
#
# LangSmith automatically records:
#
# • Prompt
# • Response
# • Tokens
# • Cost
# • Latency
llm = ChatMistralAI(
    model="mistral-small-2506",
    temperature=0
)



# ====================================================================
#                        Prompt
# ====================================================================

# Prompt template used by the chatbot.
#
# LangSmith records:
#
# • Prompt Template
# • Filled Prompt
# • User Question
# • Retrieved Context
prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        "Answer ONLY from the provided context. "
        "If not found, say you don't know."
    ),
    (
        "human",
        "Question: {question}\n\nContext:\n{context}"
    )
])



# ====================================================================
#              Helper Function
# ====================================================================

# Converts retrieved Documents into a single string.
#
# RunnableLambda makes this function part of the LangChain graph,
# therefore LangSmith also records this step.
def format_docs(docs):

    return "\n\n".join(
        doc.page_content
        for doc in docs
    )



# ====================================================================
#                Build Entire Knowledge Base
# ====================================================================

# Entire setup is recorded under the parent run
# "setup_pipeline".
vectorstore = setup_pipeline(PDF_PATH)


# Retriever fetches Top-4 similar chunks.
#
# LangSmith lets you inspect exactly WHICH chunks
# were retrieved.
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4
    }
)



# ====================================================================
#                 Parallel Runnable
# ====================================================================

# RunnableParallel executes two branches simultaneously.
#
# Branch 1
#
# User Question
#      ↓
# Retriever
#      ↓
# format_docs
#
#
# Branch 2
#
# User Question
#
#
# LangSmith visualizes both branches separately.
parallel = RunnableParallel({

    "context":
        retriever
        | RunnableLambda(format_docs),

    "question":
        RunnablePassthrough()

})



# ====================================================================
#                   Complete RAG Pipeline
# ====================================================================

# Execution Flow
#
# User Question
#        │
#        ▼
# RunnableParallel
#        │
#        ▼
# Prompt
#        │
#        ▼
# Mistral LLM
#        │
#        ▼
# Output Parser
#
# LangSmith automatically builds this execution graph.
chain = (
    parallel
    | prompt
    | llm
    | StrOutputParser()
)



# ====================================================================
#                      User Query
# ====================================================================

print("PDF RAG ready. Ask a question (Ctrl+C to exit).")

q = input("\nQ: ").strip()



# ====================================================================
#                     LangSmith Config
# ====================================================================

# Adds additional information to the trace.
config = {

    # Easy-to-read run name inside LangSmith.
    "run_name": "pdf_rag_query",

    # Helpful when filtering traces.
    "tags": [
        "rag",
        "pdf",
        "mistral",
        "faiss"
    ],

    # Stores experiment information.
    "metadata": {
        "embedding_model": "mistral-embed",
        "llm": "mistral-small-2506",
        "retriever": "FAISS",
        "top_k": 4
    }
}



# ====================================================================
#                   Execute Chain
# ====================================================================

# LangSmith records:
#
# ✓ User Question
# ✓ Retrieved Documents
# ✓ Prompt
# ✓ LLM Response
# ✓ Output Parser
# ✓ Final Answer
# ✓ Tokens
# ✓ Cost
# ✓ Latency
# ✓ Metadata
# ✓ Tags
ans = chain.invoke(
    q,
    config=config
)

print("\nA:", ans)

# Now the problem of tracing some points are get solve
# But still there is two problem 
# 1. Tracing of setup pipline and rag_query  is represent as differnt project on lagsmith we both will come in same hierarchy.
# 2. Still the whole PDF will load again and again when we run the program which is much more time consuming.